---
title: "Data & Products"
---

# Video Data

All video data and spreadsheet export from parent-report questionnaires will be openly shared on Databrary at the project end. Full videos from exemplar home visits in [Hong Kong](https://nyu.databrary.org/volume/1745/slot/72036/-) and [South Korea](https://nyu.databrary.org/volume/1745/slot/72037/-) are publicly available. Curated clips and excerpts will be shared on the new "BABIESbrary" searchable global library created as part of this project.

All videos that are collected with go through a quality assurance (QA) process in which the BABIES team will ensure that participants meet inclusion criteria and protocol adhered to, such that videos are eligible to be included in the final sample. Videos that don't pass QA may be reused for other purposes, and as needed, the collection site will be provided additional training.

## Natural activities

Researchers film one hour of natural activity, while mothers and babies go about their day. Videos contain faces and voices on camera. Mothers may go anywhere in their home, play with their babies or not, do chores, work, and bath, feed, or change their child.

::: vid
[Full 1-hour natural activity from Global BABIES - South Korea:]{.descript}

```{=html}
<video width="480" controls>
    <source src="https://nyu.databrary.org/slot/72037/0,4645248/asset/492905/download?inline=true" type="video/mp4">
</video>
```
:::

::: vid
[Full 1-hour natural activity from Global BABIES - Hong Kong:]{.descript}

```{=html}
<video width="480" controls>
    <source src="https://nyu.databrary.org/slot/72036/979047,4710862/asset/492950/download?inline=true" type="video/mp4">
</video>
```
:::

## Home environment

### House walkthrough

Researchers film the entire home, focusing on capturing child objects like toys, books, feeding items, bathing items, clothes, and sleep areas.

::: vid
[Excerpts from Global BABIES - Hong Kong:]{.descript}

```{=html}
<video width="480" controls>
    <source src="https://nyu.databrary.org/slot/72038/0,15195/asset/492940/download?inline=true" type="video/mp4">
</video>
```
:::

::: vid
[Full house walkthrough from Global BABIES - South Korea:]{.descript}

```{=html}
<video width="480" controls>
    <source src="https://nyu.databrary.org/slot/72037/4646248,6684584/asset/492906/download?inline=true" type="video/mp4">
</video>
```
:::

### 3D rendering

Researchers use Matterport 3D technology to produce a digital rendering of family's homes, including measurements of all spaces.

::: vid
[Excerpt from Global BABIES - New York:]{.descript}

```{=html}
<video width="400" controls autoplay>
    <source src="https://nyu.databrary.org/slot/72038/16195,43195/asset/492948/download?inline=true" type="video/mp4">
</video>
```
:::

# Questionnaires

Researchers orally administer parent-report questionnaires during the home visit. Questionnaires are translated into local languages by each site investigator's team. Topics covered include:

+---------------------------+-----------------------------------------+
| Before Visit (over phone) | Demographics\                           |
|                           | Gestational age & child health\         |
|                           | Home languages\                         |
|                           | Sleep & childcare                       |
+---------------------------+-----------------------------------------+
| Home Visit                | Vocabulary\                             |
|                           | Motor milestones\                       |
|                           | Division of labor\                      |
|                           | Family routines\                        |
|                           | Household roster\                       |
|                           | Child-rearing values                    |
+---------------------------+-----------------------------------------+
| After Visit               | Experimenter protocol notes\            |
|                           | Checklist for quality assurance         |
+---------------------------+-----------------------------------------+

::: vid
[Full questionnaire from Global BABIES - Hong Kong:]{.descript}

```{=html}
<video width="480" controls>
    <source src="https://nyu.databrary.org/slot/72036/4725859,6877581/asset/492904/download?inline=true" type="video/mp4">
</video>
```
:::

# Language Translations & Cultural Adaptations

## Assessing vocabulary of dual language learners

As part of the NIH [PLAY Project](play-project.org), a method for addressing gaps in the assessment of dual-language learning infants was developed. The method for developing the vocabulary inventory and product are reported are shared on [this Databrary volume](https://nyu.databrary.org/volume/1168).
